### ISSUE TITLE
Game freezes when out of range

### ISSUE THREAD

**Issue by ryan-levisky** [lferna05/owmastermind#2]
Hello- If I select a character, an then an attack, the game "freezes". I can't go back to select another activity, the game just sits there.

**Comment by lferna05** [comment]
Thank you for trying the prototype. For now, I'm focusing on testing some rules before making the "victory" or the "game over" screen :).
But yes, for the playable prototype version, I will do it.

**Comment by lferna05** [comment]
What I plan for this issue:
 - A better UI for selecting characters and targets.
 - A "Back" button.

**Comment by lferna05** [comment]
Solved in the prototype 4
